export const BOOK_MAP: Record<string, string> = {
  'Gênesis': 'genesis', 'Exodo': 'exodus', 'Êxodo': 'exodus',
  'Levítico': 'leviticus', 'Números': 'numbers', 'Deuteronômio': 'deuteronomy',
  'Josué': 'joshua', 'Juízes': 'judges', 'Rute': 'ruth',
  '1 Samuel': '1-samuel', '2 Samuel': '2-samuel',
  '1 Reis': '1-kings', '2 Reis': '2-kings',
  '1 Crônicas': '1-chronicles', '2 Crônicas': '2-chronicles',
  'Esdras': 'ezra', 'Neemias': 'nehemiah', 'Ester': 'esther',
  'Jó': 'job', 'Salmos': 'psalms', 'Salmo': 'psalms',
  'Provérbios': 'proverbs', 'Eclesiastes': 'ecclesiastes',
  'Cânticos': 'song-of-songs', 'Cantares': 'song-of-songs',
  'Isaías': 'isaiah', 'Jeremias': 'jeremiah', 'Lamentações': 'lamentations',
  'Ezequiel': 'ezekiel', 'Daniel': 'daniel',
  'Oséias': 'hosea', 'Oseias': 'hosea', 'Joel': 'joel',
  'Amós': 'amos', 'Obadias': 'obadiah', 'Jonas': 'jonah',
  'Miquéias': 'micah', 'Naum': 'nahum', 'Habacuque': 'habakkuk',
  'Sofonias': 'zephaniah', 'Ageu': 'haggai', 'Zacarias': 'zechariah',
  'Malaquias': 'malachi',
  'Mateus': 'matthew', 'Marcos': 'mark', 'Lucas': 'luke',
  'João': 'john', 'Atos': 'acts', 'Romanos': 'romans',
  '1 Coríntios': '1-corinthians', '2 Coríntios': '2-corinthians',
  'Gálatas': 'galatians', 'Efésios': 'ephesians',
  'Filipenses': 'philippians', 'Colossenses': 'colossians',
  '1 Tessalonicenses': '1-thessalonians', '2 Tessalonicenses': '2-thessalonians',
  '1 Timóteo': '1-timothy', '2 Timóteo': '2-timothy',
  'Tito': 'titus', 'Filemom': 'philemon', 'Hebreus': 'hebrews',
  'Tiago': 'james',
  '1 Pedro': '1-peter', '2 Pedro': '2-peter',
  '1 João': '1-john', '2 João': '2-john', '3 João': '3-john',
  'Judas': 'jude', 'Apocalipse': 'revelation',
};
